---
- name: Ubuntu | Create user
  user: name={{ item.user }}
        state=present
        generate_ssh_key=yes ssh_key_bits=2048 shell=/bin/bash
  with_items: users_add
  tags:
    - users


- name: Ubuntu | Create sudo
  template: src=sudo.j2 
            dest=/etc/sudoers.d/{{ item.user }} owner=root group=root mode=0440
  with_items: users_add_sudo
  tags:
    - users


- name: Ubuntu | Add public key for user
  copy: src=keys/{{use_keys}}/{{ item.user }}
        dest=/home/{{ item.user }}/.ssh/authorized_keys
        owner={{ item.user }} group={{ item.user }} mode=0600
  with_items: users_add
  tags:
    - users


- name: Ubuntu | Change password for acc
  user: >
    name="{{ item.item.user }}"
    password="{{ item.stdout }}"
  with_items: "{{ password_encrypted.results }}"
  tags:
    - users



- name: Ubuntu | Configure security SSH
  lineinfile: >
    dest=/etc/ssh/sshd_config
    state=absent
    regexp='^.*?{{ item }}'
  with_items:
    - "AllowUsers"
  tags:
    - users


- name: Ubuntu | Config ssh User allow
  lineinfile: >
    dest=/etc/ssh/sshd_config
    line='AllowUsers {{ ssh_allow_users }}'
    state=present
  notify: restart ssh
  tags:
    - users
