---


- name: Add module modprobe nf_conntrack hashsize=524288
  command: /sbin/modprobe nf_conntrack hashsize=524288
  tags:
    - sysctl


- name: Add module modprobe nf_conntrack_ipv4 hashsize=524288
  command: /sbin/modprobe nf_conntrack_ipv4 hashsize=524288
  when: ansible_distribution_major_version == "7"
  tags:
    - sysctl


- name: Add module modprobe ip_conntrack hashsize=524288
  command: /sbin/modprobe ip_conntrack hashsize=524288
  when: ansible_distribution_major_version == "6"
  tags:
    - sysctl


- name: Set nf_conntrack to rc.local
  lineinfile: >
    dest=/etc/rc.local
    line='modprobe nf_conntrack hashsize=524288'
    state=present
    insertafter=EOF
  tags:
    - sysctl


- name: Set nf_conntrack_ipv4 to rc.local
  lineinfile: >
    dest=/etc/rc.local
    line='modprobe nf_conntrack_ipv4 hashsize=524288'
    state=present
    insertafter=EOF
  when: ansible_distribution_major_version == "7"
  tags:
    - sysctl


- name: Set ip_conntrack_ipv4 to rc.local
  lineinfile: >
    dest=/etc/rc.local
    line='modprobe ip_conntrack hashsize=524288'
    state=present
    insertafter=EOF
  when: ansible_distribution_major_version == "6"
  tags:
    - sysctl


- name: Off all swap
  command: /sbin/swapoff -a
  tags:
    - sysctl


- name: Set swapoff -a to rc.local
  lineinfile: >
    dest=/etc/rc.local
    line='swapoff -a'
    state=present
    insertafter=EOF
  tags:
    - sysctl


- name: Config net.ipv4.ip_forward
  sysctl: >
    name=net.ipv4.ip_forward
    value={{ net_ipv4_ip_forward }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.all.send_redirects
  sysctl: >
    name=net.ipv4.conf.all.send_redirects
    value={{ net_ipv4_conf_all_send_redirects }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.default.send_redirects
  sysctl: >
    name=net.ipv4.conf.default.send_redirects
    value={{ net_ipv4_conf_default_send_redirects }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.all.accept_source_route
  sysctl: >
    name=net.ipv4.conf.all.accept_source_route
    value={{ net_ipv4_conf_all_accept_source_route }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.default.accept_source_route
  sysctl: >
    name=net.ipv4.conf.default.accept_source_route
    value={{ net_ipv4_conf_default_accept_source_route }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.all.accept_redirects
  sysctl: >
    name=net.ipv4.conf.all.accept_redirects
    value={{ net_ipv4_conf_all_accept_redirects }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.default.accept_redirects
  sysctl: >
    name=net.ipv4.conf.default.accept_redirects
    value={{ net_ipv4_conf_default_accept_redirects }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.all.secure_redirects
  sysctl: >
    name=net.ipv4.conf.all.secure_redirects
    value={{ net_ipv4_conf_all_secure_redirects }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.default.secure_redirects
  sysctl: >
    name=net.ipv4.conf.default.secure_redirects
    value={{ net_ipv4_conf_default_secure_redirects }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.all.log_martians
  sysctl: >
    name=net.ipv4.conf.all.log_martians
    value={{ net_ipv4_conf_all_log_martians }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.default.log_martians
  sysctl: >
    name=net.ipv4.conf.default.log_martians
    value={{ net_ipv4_conf_default_log_martians }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.icmp_echo_ignore_broadcasts
  sysctl: >
    name=net.ipv4.icmp_echo_ignore_broadcasts
    value={{ net_ipv4_icmp_echo_ignore_broadcasts }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.icmp_ignore_bogus_error_responses
  sysctl: >
    name=net.ipv4.icmp_ignore_bogus_error_responses
    value={{ net_ipv4_icmp_ignore_bogus_error_responses }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.all.rp_filter
  sysctl: >
    name=net.ipv4.conf.all.rp_filter
    value={{ net_ipv4_conf_all_rp_filter }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.conf.default.rp_filter
  sysctl: >
    name=net.ipv4.conf.default.rp_filter
    value={{ net_ipv4_conf_default_rp_filter }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config kernel.sysrq
  sysctl: >
    name=kernel.sysrq
    value={{ kernel_sysrq }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config kernel.sysrq
  sysctl: >
    name=kernel.sysrq
    value={{ kernel_sysrq }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config kernel.core_uses_pid
  sysctl: >
    name=kernel.core_uses_pid
    value={{ kernel_core_uses_pid }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config kernel.pid_max
  sysctl: >
    name=kernel.pid_max
    value={{ kernel_pid_max }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl

- name: Config net.ipv4.tcp_syncookies
  sysctl: >
    name=net.ipv4.tcp_syncookies
    value={{ net_ipv4_tcp_syncookies }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config kernel.msgmnb
  sysctl: >
    name=kernel.msgmnb
    value={{ kernel_msgmnb }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config kernel.msgmax
  sysctl: >
    name=kernel.msgmax
    value={{ kernel_msgmax }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config kernel.shmmax
  sysctl: >
    name=kernel.shmmax
    value={{ kernel_shmmax }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config kernel.shmall
  sysctl: >
    name=kernel.shmall
    value={{ kernel_shmall }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl

- name: Config net.ipv4.ip_local_port_range
  sysctl: >
    name=net.ipv4.ip_local_port_range
    value='{{ net_ipv4_ip_local_port_range }}'
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_max_tw_buckets
  sysctl: >
    name=net.ipv4.tcp_max_tw_buckets
    value={{ net_ipv4_tcp_max_tw_buckets }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.ip_nonlocal_bind
  sysctl: >
    name=net.ipv4.ip_nonlocal_bind
    value={{ net_ipv4_ip_nonlocal_bind }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.icmp_echo_ignore_all
  sysctl: >
    name=net.ipv4.icmp_echo_ignore_all
    value={{ net_ipv4_icmp_echo_ignore_all }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl

- name: Config net.ipv4.tcp_max_syn_backlog
  sysctl: >
    name=net.ipv4.tcp_max_syn_backlog
    value={{ net_ipv4_tcp_max_syn_backlog }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_synack_retries
  sysctl: >
    name=net.ipv4.tcp_synack_retries
    value={{ net_ipv4_tcp_synack_retries }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_no_metrics_save
  sysctl: >
    name=net.ipv4.tcp_no_metrics_save
    value={{ net_ipv4_tcp_no_metrics_save }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_tw_reuse
  sysctl: >
    name=net.ipv4.tcp_tw_reuse
    value={{ net_ipv4_tcp_tw_reuse }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_moderate_rcvbuf
  sysctl: >
    name=net.ipv4.tcp_moderate_rcvbuf
    value={{ net_ipv4_tcp_moderate_rcvbuf }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_retries2
  sysctl: >
    name=net.ipv4.tcp_retries2
    value={{ net_ipv4_tcp_retries2 }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_keepalive_time
  sysctl: >
    name=net.ipv4.tcp_keepalive_time
    value={{ net_ipv4_tcp_keepalive_time }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_keepalive_probes
  sysctl: >
    name=net.ipv4.tcp_keepalive_probes
    value={{ net_ipv4_tcp_keepalive_probes }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_keepalive_intvl
  sysctl: >
    name=net.ipv4.tcp_keepalive_intvl
    value={{ net_ipv4_tcp_keepalive_intvl }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_fin_timeout
  sysctl: >
    name=net.ipv4.tcp_fin_timeout
    value={{ net_ipv4_tcp_fin_timeout }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_tw_recycle
  sysctl: >
    name=net.ipv4.tcp_tw_recycle
    value={{ net_ipv4_tcp_tw_recycle }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_syn_retries
  sysctl: >
    name=net.ipv4.tcp_syn_retries
    value={{ net_ipv4_tcp_syn_retries }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_max_orphans
  sysctl: >
    name=net.ipv4.tcp_max_orphans
    value={{ net_ipv4_tcp_max_orphans }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.core.rmem_max
  sysctl: >
    name=net.core.rmem_max
    value={{ net_core_rmem_max }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.core.rmem_default
  sysctl: >
    name=net.core.rmem_default
    value={{ net_core_rmem_default }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.core.netdev_max_backlog
  sysctl: >
    name=net.core.netdev_max_backlog
    value={{ net_core_netdev_max_backlog }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_window_scaling
  sysctl: >
    name=net.ipv4.tcp_window_scaling
    value={{ net_ipv4_tcp_window_scaling }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_sack
  sysctl: >
    name=net.ipv4.tcp_sack
    value={{ net_ipv4_tcp_sack }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_timestamps
  sysctl: >
    name=net.ipv4.tcp_timestamps
    value={{ net_ipv4_tcp_timestamps }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.nf_conntrack_max
  sysctl: >
    name=net.nf_conntrack_max
    value={{ net_nf_conntrack_max }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.netfilter.nf_conntrack_max
  sysctl: >
    name=net.netfilter.nf_conntrack_max
    value={{ net_netfilter_nf_conntrack_max }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.core.wmem_max
  sysctl: >
    name=net.core.wmem_max
    value={{ net_core_wmem_max }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_wmem
  sysctl: >
    name=net.ipv4.tcp_wmem
    value='{{ net_ipv4_tcp_wmem }}'
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_mem
  sysctl: >
    name=net.ipv4.tcp_mem
    value='{{ net_ipv4_tcp_mem }}'
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.udp_mem
  sysctl: >
    name=net.ipv4.udp_mem
    value='{{ net_ipv4_udp_mem }}'
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.tcp_rmem
  sysctl: >
    name=net.ipv4.tcp_rmem
    value='{{ net_ipv4_tcp_rmem }}'
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.udp_wmem_min
  sysctl: >
    name=net.ipv4.udp_wmem_min
    value={{ net_ipv4_udp_wmem_min }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.udp_rmem_min
  sysctl: >
    name=net.ipv4.udp_rmem_min
    value={{ net_ipv4_udp_rmem_min }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config vm_overcommit_memory
  sysctl: >
    name=vm.overcommit_memory
    value={{ vm_overcommit_memory }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config vm.swappiness
  sysctl: >
    name=vm.swappiness
    value={{ vm_swappiness }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config fs.file-max
  sysctl: >
    name=fs.file-max
    value={{ fs_file_max }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config fs.suid_dumpable
  sysctl: >
    name=fs.suid_dumpable
    value={{ fs_suid_dumpable }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config kernel.randomize_va_space
  sysctl: >
    name=kernel.randomize_va_space
    value={{ kernel_randomize_va_space }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv4.route.flush
  sysctl: >
    name=net.ipv4.route.flush
    value={{ net_ipv4_route_flush }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv6.conf.all.accept_ra
  sysctl: >
    name=net.ipv6.conf.all.accept_ra
    value={{ net_ipv6_conf_all_accept_ra }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv6.route.flush
  sysctl: >
    name=net.ipv6.route.flush
    value={{ net_ipv6_route_flush }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv6.conf.all.accept_redirects
  sysctl: >
    name=net.ipv6.conf.all.accept_redirects
    value={{ net_ipv6_conf_all_accept_redirects }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv6.conf.default.accept_redirects
  sysctl: >
    name=net.ipv6.conf.default.accept_redirects
    value={{ net_ipv6_conf_default_accept_redirects }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: Config net.ipv6.conf.all.disable_ipv6
  sysctl: >
    name=net.ipv6.conf.all.disable_ipv6
    value={{ net_ipv6_conf_all_disable_ipv6 }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: net_ipv6_conf_default_disable_ipv6
  sysctl: >
    name=net.ipv6.conf.default.disable_ipv6
    value={{ net_ipv6_conf_default_disable_ipv6 }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: net.ipv6.conf.lo.disable_ipv6
  sysctl: >
    name=net.ipv6.conf.lo.disable_ipv6
    value={{ net_ipv6_conf_lo_disable_ipv6 }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl


- name: net.ipv4.tcp_challenge_ack_limit 
  sysctl: >
    name=net.ipv4.tcp_challenge_ack_limit
    value={{ net_ipv4_tcp_challenge_ack_limit }}
    state=present
    ignoreerrors=true
  tags:
    - sysctl
    - sysctl_fix


- name: Reload sysctl
  shell: sysctl -p
  ignore_errors: true
  tags:
    - sysctl
    - sysctl_fix
